### ISSUE TITLE
Failed to be used in multi-thread application

### ISSUE THREAD

**Issue by joshua19881228** [NVIDIA/VideoProcessingFramework#12]
Thank you for your effort developing this framework. It's convinient to use.  

I've been successful to start the samples you provided. However, when using thie framework in my own applicatioin, I've confronted with following problem. 

My code is like such

```python
import cv2
import PyNvCodec as nvc
from threading import Thread


class CNVCamCtrl:
    def __init__(self):
        self.thread = None
        self.is_running = False
        self.nvc_cap = None

    def __del__(self):
        self.stop()

    def connect(self, source, dev_id=0):
        print("openning %s" % source)
        try:
            self.nvc_cap = nvc.PyNvDecoder(source, dev_id)
            print("open video success")
            return True
        except:
            print("open video fail")
            self.nvc_cap = None
            return False

    def start(self, callback, size):
        self.stop()
        if self.nvc_cap is not None:
            print("start")
            self.is_running = True
            self.thread = Thread(target=self.getLoop, args=[callback, size])
            self.thread.setDaemon(True)
            self.thread.start()

    def stop(self):
        if self.thread is not None:
            self.is_running = False
            self.thread.join()
            self.thread = None

    def getLoop(self, callback, size):
        if (self.nvc_cap is not None) and self.is_running:
            width = self.nvc_cap.Width()
            print("frame width %d" % width)
            img = self.nvc_cap.DecodeSingleFrame()
            print("frame size %d" % img.size)
            if img.size:
                raw_size = (int(img.size / width), int(width))
            while (img.size) and self.is_running:
                img = self.nvc_cap.DecodeSingleFrame()
                img = img.reshape(raw_size)
                img = cv2.cvtColor(img, cv2.COLOR_YUV2BGR_NV12)
                img = cv2.resize(img, size)
                callback(img)


if __name__ == "__main__":
    import time

    def callback(img):
        cv2.imshow("img", img)
        cv2.waitKey(1)

    cam_ctrl = CNVCamCtrl()
    cam_ctrl.connect(
        "rtsp://admin:tztx1234@192.168.50.108:554/cam/realmonitor?channel=1&subtype=0"
    )
    cam_ctrl.start(callback, (320, 240))
    time.sleep(10)
    cam_ctrl.stop()
```

The log I got is 

```
openning rtsp://admin:tztx1234@192.168.50.108:554/cam/realmonitor?channel=1&subtype=0
Decoding on GPU 0
[udp @ 0000024dfd606a40] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 0000024dfd618ec0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[-----] Media format: RTSP input (rtsp)
[-----] 27 RTSP input
open video success
start
frame width 1920
frame size 0
```

I can get it work if I directly put `getLoop` in `start` other than run `getLoop` in a thread.

```python
    def start(self, callback, size):
        self.stop()
        if self.nvc_cap is not None:
            print("start")
            self.is_running = True
            self.getLoop(callback, size)
            # self.thread = Thread(target=self.getLoop, args=[callback, size])
            # self.thread.setDaemon(True)
            # self.thread.start()
```

Would you please give me any advice or suggestion to fix it? Thank you.

**Comment by rarzumanyan** [comment]
Hi,
VPF creates new instance of numpy array each time the `DecodeSingleFrame` is called so theoretically it shouldn't cause multi-threading issues. Can you please try with `getLoop` method done as follows? 

```python
def getLoop(self, callback, size):       
    while (self.nvc_cap is not None) and self.is_running:
        # img is 1920x1080 NV12 picture, so it's 1920 * 1620 array of uint8
        img = self.nvc_cap.DecodeSingleFrame().reshape(1620, 1920)
        if not (img.size):
            break

        img = cv2.cvtColor(img, cv2.COLOR_YUV2BGR_NV12)
        img = cv2.resize(img, size)
        callback(img)
```

Just one more thing from side, I don't know how the 
```python
def callback(img):
    cv2.imshow("img", img)
    cv2.waitKey(1)
```
will behave if run in separate thread. Can you try it with something simpler, like writing to file?

**Comment by joshua19881228** [comment]
@rarzumanyan 

The output is 

```
openning rtsp://admin:tztx1234@192.168.50.108:554/cam/realmonitor?channel=1&subtype=0
Decoding on GPU 0
[udp @ 00000175369e6a40] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 00000175369f8ec0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[-----] Media format: RTSP input (rtsp)
[-----] 27 RTSP input
open video success
start
Exception in thread Thread-1:
Traceback (most recent call last):
  File "d:\libs\python36\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "d:\libs\python36\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".\nv_test.py", line 44, in getLoop
    img = self.nvc_cap.DecodeSingleFrame().reshape(1620, 1920)
ValueError: cannot reshape array of size 0 into shape (1620,1920)
```
It indicates that `self.nvc_cap.DecodeSingleFrame()` got a 0 size numpy

Besides, I modify `callback` to 

```python
    def callback(img):
        print(img.shape)
```

**Comment by macosala** [comment]
I've experienced similar issue with EncodeSingleFrame() in separated thread... so let me share my experience. 

In my case, cuMemAllocPitch() failed to allocate memory and throw excetion "Failed to do cuMemAllocPitch".
I've found that cuMemAllocPitch() returns CUDA_ERROR_INVALID_CONTEXT when it's located different thread from nvEnc created. 

I solved the memory allocation issue by simply placing all nvc related objects in same thread. 
(In case of your code, _self.nvc_cap = nvc.PyNvDecoder(source, dev_id)_  maybe moved into getLoop...)

**Comment by joshua19881228** [comment]
@macosala Exactly. I've been using it just as you did.

**Comment by niaoyu** [comment]
Hi , have you tried to decode multi rtmps at the same time

I just meet the same error here, but I could not decode rtmp urls in just one thread I guess

**Comment by rarzumanyan** [comment]
Hi @niaoyu,
Please check out mt_fixes branch, it has recent multi-thread issues fixed. You can reference SampleDecodeMultiThread.py which can also decode RTSP streams.

**Comment by joshua19881228** [comment]
@raz

> Hi @niaoyu,
> Please check out mt_fixes branch, it has recent multi-thread issues fixed. You can reference SampleDecodeMultiThread.py which can also decode RTSP streams.

That's cool. Close this issue.
