### ISSUE TITLE
SampleDecode.py "RuntimeError: Error initializing filter_units=pass_types=6 bitstream filter: Bitstream filter not found"

### ISSUE THREAD

**Issue by hadeson** [NVIDIA/VideoProcessingFramework#122]
**Describe the bug**
Running SampleDecode.py got this error on all mp4, mov videos that I tested.
python SampleDecode.py 0 ../big_buck_bunny_480p_h264.mov ../bunny_out
Decoding on GPU 0
Traceback (most recent call last):
  File "SampleDecode.py", line 55, in <module>
    decode(gpuID, encFilePath, decFilePath)
  File "SampleDecode.py", line 22, in decode
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
RuntimeError: Error initializing filter_units=pass_types=6 bitstream filter: Bitstream filter not found

**To Reproduce**
Compile as described in the Wiki using CUDA SDK 10.2, Video_Codec_SDK_9.1.23, ffmpeg from source

cmake .. -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DCMAKE_INSTALL_PREFIX:PATH=/home/sonct/dev/VideoProcessingFramework -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPYTHON_EXECUTABLE=/usr/bin/python3.8

No errors, SampleEncode.py work.

**Desktop:**
 - OS: Ubuntu 18.04 64bit
 - Nvidia driver version: 440.33.01
 - CUDA Version 10.2
 - Video Codec SDK Version 9.1.23
 - Python Version 3.8

**Comment by rarzumanyan** [comment]
Hi @hadeson 

Your ffmpeg build doesn't support `filter_units` bitstream filter which is required for SEI extraction.

**Comment by hadeson** [comment]
Hi @rarzumanyan 

I rebuilt ffmpeg with filter_units. `$ffmpeg -i input.mkv -codec copy -bsf:v 'filter_units=pass_types=6' output.mkv` run successfully. Still rebuild VPF and run SampleDecode.py give the same error.

Here is output of `$ffmpeg -bsfs`

> Bitstream filters:
> aac_adtstoasc
> av1_frame_merge
> av1_frame_split
> av1_metadata
> chomp
> dump_extra
> dca_core
> eac3_core
> extract_extradata
> filter_units
> h264_metadata
> h264_mp4toannexb
> h264_redundant_pps
> hapqa_extract
> hevc_metadata
> hevc_mp4toannexb
> imxdump
> mjpeg2jpeg
> mjpegadump
> mp3decomp
> mpeg2_metadata
> mpeg4_unpack_bframes
> mov2textsub
> noise
> null
> opus_metadata
> pcm_rechunk
> prores_metadata
> remove_extra
> text2movsub
> trace_headers
> truehd_core
> vp9_metadata
> vp9_raw_reorder
> vp9_superframe
> vp9_superframe_split
>

**Comment by rarzumanyan** [comment]
Hi @hadeson 

Please check that in the runtime VPF loads same FFmpeg libraries it was linked against.
This sometimes may happen when multiple FFmpeg versions co-exist on the same machine.

**Comment by hadeson** [comment]
Fresh install on another machine solve the issue. Thanks for your help!
