### ISSUE TITLE
undefined symbol: cuvidDestroyDecoder

### ISSUE THREAD

**Issue by splinter21** [NVIDIA/VideoProcessingFramework#145]
**Describe the bug**
Traceback (most recent call last):
  File "SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ImportError: /data/docker/liujing04/ff-vpf/VideoProcessingFramework/install/bin/libTC.so: undefined symbol: cuvidDestroyDecoder

**To Reproduce**
export PATH_TO_SDK=Video_Codec_SDK_9.1.23
export PATH_TO_FFMPEG=/data/docker/liujing04/ff-vpf/FFmpeg/build_x64_release_shared
export CUDACXX=/usr/local/cuda/bin/nvcc
export INSTALL_PREFIX=$(pwd)/install
mkdir -p install
mkdir -p build
cd build
cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="1" \
  -DPYTHON_LIBRARY=/root/anaconda3/lib/libpython3.7m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
make -j48 && make install

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Nvidia driver version  396.44
 - CUDA Version 10.1
 - Video Codec SDK Version 9.1.23
 - Python Version 3.7

**Additional context**
I successfully configure+make+make install it. But got a ImportError when using py3.7

**Comment by splinter21** [comment]
root@6369b06104f4:/data/docker/liujing04/crash# ldd /data/docker/liujing04/ff-vpf/VideoProcessingFramework/install/bin/PyNvCodec.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffcc79be000)
	libTC.so => /data/docker/liujing04/ff-vpf/VideoProcessingFramework/build/PyNvCodec/TC/libTC.so (0x00007fdc485b5000)
	libpython3.7m.so.1.0 => /root/anaconda3/lib/libpython3.7m.so.1.0 (0x00007fdc4824e000)
	libTC_CORE.so => /data/docker/liujing04/ff-vpf/VideoProcessingFramework/build/PyNvCodec/TC/TC_CORE/libTC_CORE.so (0x00007fdc48049000)
	libcudart.so.10.1 => /usr/local/cuda/lib64/libcudart.so.10.1 (0x00007fdc47dcd000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007fdc46c46000)
	libstdc++.so.6 => /root/anaconda3/lib/libstdc++.so.6 (0x00007fdc48c23000)
	libgcc_s.so.1 => /root/anaconda3/lib/libgcc_s.so.1 (0x00007fdc48c0e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc46855000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc46636000)
	libavutil.so.56 => /data/docker/liujing04/ff-vpf/FFmpeg/build_x64_release_shared/lib/libavutil.so.56 (0x00007fdc46183000)
	libavcodec.so.58 => /data/docker/liujing04/ff-vpf/FFmpeg/build_x64_release_shared/lib/libavcodec.so.58 (0x00007fdc44b88000)
	libavformat.so.58 => /data/docker/liujing04/ff-vpf/FFmpeg/build_x64_release_shared/lib/libavformat.so.58 (0x00007fdc44711000)
	libnppig.so.10 => /usr/local/cuda/lib64/libnppig.so.10 (0x00007fdc42c3f000)
	libnppicc.so.10 => /usr/local/cuda/lib64/libnppicc.so.10 (0x00007fdc42602000)
	libnppidei.so.10 => /usr/local/cuda/lib64/libnppidei.so.10 (0x00007fdc41c12000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc41a0e000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fdc4180b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdc41603000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc41265000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdc48b4a000)
	libnvidia-fatbinaryloader.so.418.165.02 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.418.165.02 (0x00007fdc41017000)
	libswresample.so.3 => not found
	libnppc.so.10 => /usr/local/cuda-10.1/targets/x86_64-linux/lib/libnppc.so.10 (0x00007fdc40d9c000)
root@6369b06104f4:/data/docker/liujing04/crash# ldd /data/docker/liujing04/ff-vpf/VideoProcessingFramework/install/bin/PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffecf733000)
	libc10.so => not found
	libtorch.so => not found
	libtorch_cpu.so => not found
	libtorch_python.so => not found
	libcudart.so.10.1 => /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1 (0x00007f3778267000)
	libc10_cuda.so => not found
	libtorch_cuda.so => not found
	libstdc++.so.6 => /root/anaconda3/lib/libstdc++.so.6 (0x00007f377859d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3777ec9000)
	libgcc_s.so.1 => /root/anaconda3/lib/libgcc_s.so.1 (0x00007f3778588000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3777caa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f37778b9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f37784e3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f37776b5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f37774ad000)

**Comment by splinter21** [comment]
libtorch*.so
libc*.so
are not found?
They are here
![1111](https://user-images.githubusercontent.com/26759495/103391174-f7b27000-4b52-11eb-802e-3f587c3e736d.png)

**Comment by splinter21** [comment]
Traceback (most recent call last):
  File "SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ImportError: libswresample.so.3: cannot open shared object file: No such file or directory

libswresample.so.3 => not found

but libswresample.so.3 is here:/data/docker/liujing04/ff-vpf/FFmpeg/build_x64_release_shared/lib
