### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by 2899193288** [NVIDIA/VideoProcessingFramework#152]
**Describe the bug**
Hi, I used SampleDecode.py for test, then I got a "MemoryError: std::bad_alloc". I don't know how to solve it.

**To Reproduce**
`python3 SampleDecode.py 0 rtsp://3.84.6.190/vod/mp4:BigBuckBunny_115k.mov ./publish.flv`
Usage: SampleDecode.py $gpu_id $input_file $output_file
Decoding on GPU 0
[rtsp @ 0x135bc80] max delay reached. need to consume packet
[rtsp @ 0x135bc80] RTP: missed 1 packets
[rtsp @ 0x135bc80] max delay reached. need to consume packet
[rtsp @ 0x135bc80] RTP: missed 2 packets
[rtsp @ 0x135bc80] max delay reached. need to consume packet
[rtsp @ 0x135bc80] RTP: missed 2 packets
[rtsp @ 0x135bc80] max delay reached. need to consume packet
[rtsp @ 0x135bc80] RTP: missed 2 packets
[rtsp @ 0x135bc80] max delay reached. need to consume packet
[rtsp @ 0x135bc80] RTP: missed 1 packets
Traceback (most recent call last):
  File "SampleDecode.py", line 50, in <module>
    decode(gpuID, encFilePath, decFilePath)
  File "SampleDecode.py", line 23, in decode
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
MemoryError: std::bad_alloc

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.7 LTS (Xenial Xerus)
 - Nvidia driver version 450.80.02
 - CUDA Version 10.1
 - Video Codec SDK Version 9.1.23
 - Python Version 3.7.6

**Comment by 2899193288** [comment]
I reboot, then it's ok. I'am sorry.
