### ISSUE TITLE
Problem occurred when I use multiprocessing with VPF encoding, need help!

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#161]
**Describe the bug**
Problem occurred when I run two encoding process on one GPU (GeForce RTX 3090) as follows:

```
Traceback (most recent call last):
  File "./multiprocessing/ending_data_manager.py", line 39, in flush_avaliable_frames
    video_writer.write(output_img)
  File "./util/video.py", line 25, in write
    success, encByteArray = self.convert_numpy_to_nv12(bgr_frame)
  File "./util/video.py", line 45, in convert_numpy_to_nv12
    success = self.nvEnc.EncodeSingleSurface(cvtSurface, encFrame, sync=False)
RuntimeError: NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 10
Description: EncodeAPI Internal Error.
 at ./VideoProcessingFramework/PyNvCodec/TC/src/NvEncoder.cpp:84
```

It is worth mentioning that the problem only appear on my GeForce RTX 3090 GPU, but not appear on my Tesla V100 GPU. 

I notice the error "EncodeAPI Internal Error." appears near the code "nvEncOpenEncodeSessionEx" in VPF source code, so I look up the [NvEncodeAPI doc](https://developer.download.nvidia.cn/assets/cuda/files/NvEncodeAPI_v.6.0.pdf). It seems that the error means that a process cannot open an encoding session.

<img width="754" alt="截屏2021-02-05 11 31 26" src="https://user-images.githubusercontent.com/22371026/106986160-c3f7e500-67a5-11eb-909a-8f7b9e679b6e.png">

Further, I find the number of NVENC/CHIP is different between Tesla V100 and RTX 3090. As the [website](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new#Encoder) shows, Tesla V100 has 3 NVENC/CHIP, and RTX 3090 only has 1. I wonder whether the difference caused this error in my mutiprocessing application. 

Please give me some advice, thanks a lot.

<img width="1355" alt="截屏2021-02-05 11 31 18" src="https://user-images.githubusercontent.com/22371026/106986142-b8a4b980-67a5-11eb-8cbd-2c2e9a002436.png">

**Desktop (please complete the following information):**
- OS: ubuntu 20.04
- Nvidia driver version: 460.32.03
- CUDA Version: 11.1
- Video Codec SDK Version: 9.1.23
- Python Version: 3.8.5

**Comment by TracelessLe** [comment]
Solved! Use [nvidia-patch](https://github.com/keylase/nvidia-patch).  😄
