### ISSUE TITLE
Codec 'unknown' (0) is not supported by the bitstream filter 'h264_mp4toannexb'.

### ISSUE THREAD

**Issue by royinx** [NVIDIA/VideoProcessingFramework#343]
When I build NvDecode docker container with latest FFmpeg , the container always built successfully. 
But the following error raised when run `SampleDecode.py`, even `test_PyFfmpegDemuxer.py`

>[h264_mp4toannexb @ 0x15da580] Codec 'unknown' (0) is not supported by the bitstream filter 'h264_mp4toannexb'. Supported codecs are: h264 (27) 

```
root@115d4cba7ec1:/opt/dist/bin# python3 SampleDecode.py --gpu-id 0 -e bikes.mp4  -r  bikes_out -v 
bikes.mp4
[h264_mp4toannexb @ 0x15da580] Codec 'unknown' (0) is not supported by the bitstream filter 'h264_mp4toannexb'. Supported codecs are: h264 (27) 
Traceback (most recent call last):
  File "SampleDecode.py", line 353, in <module>
    dec = NvDecoder(
  File "SampleDecode.py", line 85, in __init__
    self.nv_dmx = nvc.PyFFmpegDemuxer(enc_file)
RuntimeError: Error initializing h264_mp4toannexb bitstream filter: Invalid argument
```

**Comment by rarzumanyan** [comment]
Hello @royinx 

Please run `ffprobe bikes.mp4` and share the output.

**Comment by rarzumanyan** [comment]
@royinx 

Could you please share the video?

>Then, I'm thinking is that missing nvcodec flag when compiling? and recompile with nv-codec-headers and flags.

That's not required. FFMpeg is used only to extract video stream from container.

**Comment by royinx** [comment]
`bikes.mp4` is the example video from [README](https://github.com/NVIDIA/VideoProcessingFramework#docker-instructions-linux)
`wget http://www.scikit-video.org/stable/_static/bikes.mp4`

Here is the dockerfile I used, 
Since the codec keeps showing unknown, I removed the multi-build part until the example run successfully.
I also removed the flag to build ffmpeg as you said. 
(`--enable-cuda --enable-nvenc --enable-cuvid --enable-nonfree --enable-cuda-nvcc`)

```dockerfile
# syntax=docker/dockerfile:experimental
FROM docker.io/nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04 as build

ENV POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VERSION=1.1.7

ENV PATH="/opt/.venv/bin:$POETRY_HOME/bin:$PATH" \
    PYTHON_BINARY="/opt/.venv/bin/python"

ARG GEN_PYTORCH_EXT
ARG GEN_OPENGL_EXT

RUN apt update && DEBIAN_FRONTEND=noninteractive \
    apt -y install \
    git wget cmake \
    build-essential curl \
    libavcodec-dev libavformat-dev libswscale-dev \
    libxvidcore-dev x264 libx264-dev libfaac-dev \
    libmp3lame-dev libtheora-dev libvorbis-dev \
    libglu1-mesa-dev freeglut3-dev \
    python3.8 python3-pip python3.8-venv && \
    rm -rf /var/lib/apt/lists/*

# https://python-poetry.org/docs/
WORKDIR $POETRY_HOME
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3

WORKDIR /opt

COPY docker/Makefile docker/Makefile
COPY poetry.lock poetry.lock
COPY pyproject.toml pyproject.toml
COPY docker/poetry-env.sh docker/poetry-env.sh

# Build poetry virtual environment
RUN bash docker/poetry-env.sh PYTHON_BINARY=$PYTHON_BINARY GEN_PYTORCH_EXT="$GEN_PYTORCH_EXT" GEN_OPENGL_EXT="$GEN_OPENGL_EXT"

# Build vpf
COPY . .

# RUN wget https://github.com/FFmpeg/nv-codec-headers/releases/download/n11.1.5.1/nv-codec-headers-11.1.5.1.tar.gz && \
#     tar -xvf nv-codec-headers-11.1.5.1.tar.gz && \ 
#     mv nv-codec-headers-11.1.5.1 nv-codec-headers  && \
#     cd nv-codec-headers && make install PREFIX=/usr && cd ..

RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git && \ 
    cd nv-codec-headers && make install && cd .. && \ 
    git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/ && \ 
    apt-get update && apt-get install -y build-essential yasm cmake libtool libc6 libc6-dev unzip wget libnuma1 libnuma-dev && \ 
    cd ffmpeg && \
    ./configure --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared --disable-x86asm && \ 
    make -j 8 && \
    make install 

RUN pip3 install install torch
RUN make -f docker/Makefile vpf_built \
                            PYTHON_BINARY=$PYTHON_BINARY \
                            VIDEO_CODEC_SDK=/opt/Video_Codec_SDK \
                            GEN_PYTORCH_EXT=0

# FROM docker.io/nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    git build-essential libbsd0 \
    wget cmake libtbb-dev \
    libjpeg8-dev libpng-dev libtiff-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libdc1394-22-dev libssl-dev \
    libxine2-dev libv4l-dev \
    libboost-all-dev libdc1394-22-dev \
    libglu1-mesa-dev freeglut3-dev \
    python3.8 python3-pip python3.8-venv curl

ENV POETRY_HOME="/opt/poetry"

ENV PATH="/opt/.venv/bin:$POETRY_HOME/bin:$PATH" \
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/dist:/opt/dist/bin:/opt/.venv/lib/python3.8/site-packages/torch/lib" \
    PYTHONPATH=/opt/.venv/bin:/opt/dist:/opt/dist/bin

ENTRYPOINT ["/bin/bash"]
```
Then build and run the example with 
```bash
docker-compose -f docker/docker-compose.yml build vpf
docker-compose -f docker/docker-compose.yml run vpf

cd dist/bin/
wget http://www.scikit-video.org/stable/_static/bikes.mp4
python3 SampleDecode.py --gpu-id 0 -e bikes.mp4  -r  bikes_out -v 
```

**Comment by sandhawalia** [comment]
Hey @royinx i came across the same issue. Here's something that might help. I noticed that incorrect ffmpeg (apt-get installed, [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/343#issuecomment-1160223196)) libs were being linked. Instead of the libs build from ffmpeg `master`

```
ldd dist/bin/PyNvCodec.cpython-38-x86_64-linux-gnu.so

       libavutil.so.56 => /lib/x86_64-linux-gnu/libavutil.so.56 (0x00007f3ac4f74000)
       libavcodec.so.58 => /lib/x86_64-linux-gnu/libavcodec.so.58 (0x00007f3ac39b1000)
       libavformat.so.58 => /lib/x86_64-linux-gnu/libavformat.so.58 (0x00007f3ac3737000)

```

During the cmake configuration stage I had to force few FFMPEG paths to prevent this from happening. Something on the lines of 

```
3. VPF user CMake find_library to locate ffmpeg which searches default paths (such as e. g. /usr/lib) first and user-provided path second. Make sure you link VPF against desired ffmpeg version.
```

Add the following options. 
```
            -D AVUTIL_LIBRARY=$FFMPEG/lib/libavutil.so 
            -D AVCODEC_LIBRARY=$FFMPEG/lib/libavcodec.so 
            -D AVFORMAT_LIBRARY=$FFMPEG/lib/libavformat.so 
            -D SWRESAMPLE_LIBRARY=$FFMPEG/lib/libswresample.so
```

Then follow the build recipe. as usual 

```
ldd dist/bin/PyNvCodec.cpython-38-x86_64-linux-gnu.so

        libavutil.so.57 => /home/perception/workspace/FFmpeg/build_x64_release_shared/lib/libavutil.so.57 (0x00007f3e8c029000)
        libavcodec.so.59 => /home/perception/workspace/FFmpeg/build_x64_release_shared/lib/libavcodec.so.59 (0x00007f3e8aeb6000)
        libavformat.so.59 => /home/perception/workspace/FFmpeg/build_x64_release_shared/lib/libavformat.so.59 (0x00007f3e8ac41000)
        libswresample.so.4 => /home/perception/workspace/FFmpeg/build_x64_release_shared/lib/libswresample.so.4 (0x00007f3e8664a000)
```

You can also get the updated [Dockerfile](https://github.com/NVIDIA/VideoProcessingFramework/blob/d128e7eec34dcd0f62458793be6e7b4b494b5471/docker/Dockerfile.gpu) which does everything for you. Currently under [review](https://github.com/NVIDIA/VideoProcessingFramework/pull/368)

**Comment by gedoensmax** [comment]
@royinx did the issue resolve ? If so please close.
