### ISSUE TITLE
Run SampleDecode.py and raise "CUDA error with code 17679344"

### ISSUE THREAD

**Issue by saicoco** [NVIDIA/VideoProcessingFramework#386]
**Describe the bug**
when I run SampleDecode.py after building finished, raise the error `python3 ./SampleDecode.py 0 test.mp4 test1.mp4`:
```
This sample decodes input video to raw NV12 file on given GPU.
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Traceback (most recent call last):
  File "./SampleDecode.py", line 298, in <module>
    dec = NvDecoder(gpu_id, enc_filePath, decFilePath)
  File "./SampleDecode.py", line 75, in __init__
    gpu_id)
RuntimeError: /workdir/vpf_processing/VideoProcessingFramework-ver_1.1.1/PyNvCodec/TC/src/NvDecoder.cpp:626
CUDA error with code 35331168
No error string available
```
**To Reproduce**
VPF is awosome ,and I want use it to decode videos on GPU(A30). I just build from source refer to wiki. here is the cmake scripts as following:
```bash
export PATH_TO_SDK=/workdir/vpf_processing/Video_Codec_SDK_11.1.5
export PATH_TO_FFMPEG=workdir/vpf_processing/ffmpeg-4.4/build_x64_release_shared

# Export path to CUDA compiler (you may need this sometimes if you install drivers from Nvidia site):
export CUDACXX=/usr/local/cuda/bin/nvcc

# Now the build itself
export INSTALL_PREFIX=$(pwd)/install
mkdir -p install
mkdir -p build
cd build
# If you want to generate Pytorch extension, set up corresponding CMake value GENERATE_PYTORCH_EXTENSION
cmake3 .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="0" \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
make && make install
```

build successfully and run `ldd PyNvCodec.cpython-36m-x86_64-linux-gnu.so` can get following info:

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/7789012/199705799-48c3059e-9d9a-4635-a7c0-bc19bb8c7742.png">

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Nvidia driver version: 470.82.01
 - CUDA Version [11.4]
 - Video Codec SDK Version [11.1.5]
 - Python Version [3.6]

What is the best config of CUDA, driver-version, video_codec_sdk

waitting for you reply, thanks!

**Comment by saicoco** [comment]
error with libnvcuvid.so, re-linking with /usr/lib64/libnvcuvid.so.4xxxx works
