### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by JunkangLiu** [NVIDIA/VideoProcessingFramework#415]
**Describe the bug**
Calling the PytorchNvCodec raises following exception
RuntimeError: CUDA error: invalid device ordinal
`Traceback (most recent call last):
  File "SamplePyTorch.py", line 201, in <module>
    main(gpu_id, encFilePath, decFilePath)
  File "SamplePyTorch.py", line 164, in main
    src_tensor = surface_to_tensor(rgb_pln)
  File "SamplePyTorch.py", line 87, in surface_to_tensor
    img_tensor = pnvc.DptrToTensor(surf_plane.GpuMem(),
RuntimeError: CUDA error: invalid device ordinal
`
`Traceback (most recent call last):
  File "SampleTorchResnet.py", line 1158, in <module>
    run_inference_on_video(gpu_id, input_video)
  File "SampleTorchResnet.py", line 1122, in run_inference_on_video
    img_tensor = pnvc.makefromDevicePtrUint8(surf_plane.GpuMem(),
RuntimeError: CUDA error: invalid device ordinal
`

**To Reproduce**
This function raises the exception

```
surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(), surfPlane.Height(),
                                                         surfPlane.Pitch(), surfPlane.ElemSize())
```

**Expected behavior**
Work without exception.

I don't have libtorch installed
Whether to call PytorchNvCodec must install libtorch？

**Comment by theHamsta** [comment]
Can you debug which device id is used in `makefromDevicePtrUint8` by printing the return value of `get_device_id` https://github.com/theHamsta/VideoProcessingFramework/blob/9f97990be15ecfc4ccbbe7dab09807c86c30615d/C:\dev\VideoProcessingFramework\src\PytorchNvCodec\src\PytorchNvCodec.cpp#L50 ? Probably a return value of `get_device_id` is not handled correctly

> Whether to call PytorchNvCodec must install libtorch？

No, this shouldn't be necessary. It will use the binaries from the `torch` pip package.

**Comment by JunkangLiu** [comment]
`torch::Tensor makefromDevicePtrUint8(CUdeviceptr ptr, uint32_t width,
                                     uint32_t height, uint32_t pitch,
                                     uint32_t elem_size, size_t str = 0U)
{

  auto codeid = get_device_id((void*)ptr);
    std::stringstream ss1;
    ss1 << codeid;
    throw std::runtime_error(ss1.str());`

`(py38) super@super-Precision-3650-Tower:~/installs/VideoProcessingFramework/install/bin$ python SampleTensorRTResnet.py 0 test.mp4`

`[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation end: CPU 1955 MiB, GPU 1240 MiB
Traceback (most recent call last):
  File "SampleTensorRTResnet.py", line 1294, in <module>
    infer_on_video(gpu_id, input_video, trt_file)
  File "SampleTensorRTResnet.py", line 1261, in infer_on_video
    img_tensor = pnvc.makefromDevicePtrUint8(surf_plane.GpuMem(),
RuntimeError: 2
`

我指定了gpu id=0，但似乎get device id方法的得到的gpu id=2
