### ISSUE TITLE
Failing to pip install on Windows

### ISSUE THREAD

**Issue by imdat1guy** [NVIDIA/VideoProcessingFramework#507]
**Describe the bug**
I am trying to pip install the library on windows 10 but it's failing and I'am not sure why.

**To Reproduce**
1. I have C++ build tools installed with visual studio
2. Installed CUDA 11.7
3. Got precompiled FFMPEG binaries and set the path with:
set SKBUILD_CONFIGURE_OPTIONS="-DTC_FFMPEG_ROOT=C:/path/to/your/ffmpeg/installation/ffmpeg/" 
4. Running pip install . --verbose gives me the following output:

(ballspot311) E:\Passion Projects\AI\Football Machine Vision\testing stuff\VideoProcessingFramework>pip install . --verbose
Using pip 23.2.1 from C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip (python 3.11)
Processing e:\passion projects\ai\football machine vision\testing stuff\videoprocessingframework
  Running command pip subprocess to install build dependencies
  Ignoring ninja: markers 'platform_system != "Windows"' don't match your environment
  Collecting setuptools>=42
    Obtaining dependency information for setuptools>=42 from https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl.metadata
    Using cached setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
  Collecting scikit-build
    Obtaining dependency information for scikit-build from https://files.pythonhosted.org/packages/fa/af/b3ef8fe0bb96bf7308e1f9d196fc069f0c75d9c74cfaad851e418cc704f4/scikit_build-0.17.6-py3-none-any.whl.metadata
    Using cached scikit_build-0.17.6-py3-none-any.whl.metadata (14 kB)
  Collecting numpy
    Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/2f/2a/34fe0b64e78347f4ea128868df0034a97e0f92b476f62947b0976caba820/numpy-1.25.1-cp311-cp311-win_amd64.whl.metadata
    Using cached numpy-1.25.1-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
  Collecting cmake>=3.21
    Obtaining dependency information for cmake>=3.21 from https://files.pythonhosted.org/packages/78/cf/42d206fc2679902e9408688a6e75215215e7781faf88653b2738c599e70a/cmake-3.27.0-py2.py3-none-win_amd64.whl.metadata
    Using cached cmake-3.27.0-py2.py3-none-win_amd64.whl.metadata (6.9 kB)
  Collecting distro (from scikit-build)
    Using cached distro-1.8.0-py3-none-any.whl (20 kB)
  Collecting packaging (from scikit-build)
    Using cached packaging-23.1-py3-none-any.whl (48 kB)
  Collecting wheel>=0.32.0 (from scikit-build)
    Obtaining dependency information for wheel>=0.32.0 from https://files.pythonhosted.org/packages/17/11/f139e25018ea2218aeedbedcf85cd0dd8abeed29a38ac1fda7f5a8889382/wheel-0.41.0-py3-none-any.whl.metadata
    Using cached wheel-0.41.0-py3-none-any.whl.metadata (2.2 kB)
  Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Using cached scikit_build-0.17.6-py3-none-any.whl (84 kB)
  Using cached numpy-1.25.1-cp311-cp311-win_amd64.whl (15.0 MB)
  Using cached cmake-3.27.0-py2.py3-none-win_amd64.whl (34.6 MB)
  Using cached wheel-0.41.0-py3-none-any.whl (64 kB)
  Installing collected packages: cmake, wheel, setuptools, packaging, numpy, distro, scikit-build
  Successfully installed cmake-3.27.0 distro-1.8.0 numpy-1.25.1 packaging-23.1 scikit-build-0.17.6 setuptools-68.0.0 wheel-0.41.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Traceback (most recent call last):
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
      parsed = _parse_requirement(requirement_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 115, in _parse_requirement_details
      marker = _parse_requirement_marker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
      tokenizer.raise_syntax_error(
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\_tokenizer.py", line 165, in raise_syntax_error
      raise ParserSyntaxError(
  setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after URL and whitespace)
      PytorchNvCodec @ file://E:\Passion Projects\AI\Football Machine Vision\testing stuff\VideoProcessingFramework/src/PytorchNvCodec/
                       ~~~~~~~~~~~~~~~~~~^

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\dist.py", line 290, in check_extras
      list(itertools.starmap(_check_extra, value.items()))
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\dist.py", line 306, in _check_extra
      list(_reqs.parse(reqs))
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
      raise InvalidRequirement(str(e)) from e
  setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after URL and whitespace)
      PytorchNvCodec @ file://E:\Passion Projects\AI\Football Machine Vision\testing stuff\VideoProcessingFramework/src/PytorchNvCodec/
                       ~~~~~~~~~~~~~~~~~~^

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 21, in <module>
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 488, in setup
      ) = _parse_setuptools_arguments(kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 207, in _parse_setuptools_arguments
      dist = upstream_Distribution(setup_attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\dist.py", line 486, in __init__
      _Distribution.__init__(
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
      self.finalize_options()
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\dist.py", line 925, in finalize_options
      ep(self)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\dist.py", line 945, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-u9u7ioss\overlay\Lib\site-packages\setuptools\dist.py", line 292, in check_extras
      raise DistutilsSetupError(
  distutils.errors.DistutilsSetupError: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\PC\anaconda3\envs\ballspot311\python.exe' 'C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\PC\AppData\Local\Temp\tmpx9jnhtd8'
  cwd: E:\Passion Projects\AI\Football Machine Vision\testing stuff\VideoProcessingFramework
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nvidia driver version: 536.67
 - CUDA Version V11.7.64
 - Python Version: tried on 3.9.16 and 3.11.4

**Comment by FredeJ** [comment]
I'm getting the same issue, when trying to `pip install`.

**Comment by FredeJ** [comment]
It seems my issue was related to a space in the path. It seems @imdat1guy also has a space in his path (`E:\Passion Projects\AI\Football Machine Vision\testing stuff\VideoProcessingFramework`).

Moving the directory to a path with no spaces solved my issue and I was able to install.

**Comment by imdat1guy** [comment]
I changed the path so that there's no spaces but I'm still facing issues. Seems like something goes wrong with CMake.


Output:

(ballspot311) E:\repos\VideoProcessingFramework>pip install . --verbose
Using pip 23.2.1 from C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip (python 3.11)
Processing e:\repos\videoprocessingframework
  Running command pip subprocess to install build dependencies
  Ignoring ninja: markers 'platform_system != "Windows"' don't match your environment
  Collecting setuptools>=42
    Obtaining dependency information for setuptools>=42 from https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl.metadata
    Using cached setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
  Collecting scikit-build
    Obtaining dependency information for scikit-build from https://files.pythonhosted.org/packages/fa/af/b3ef8fe0bb96bf7308e1f9d196fc069f0c75d9c74cfaad851e418cc704f4/scikit_build-0.17.6-py3-none-any.whl.metadata
    Using cached scikit_build-0.17.6-py3-none-any.whl.metadata (14 kB)
  Collecting numpy
    Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
    Using cached numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
  Collecting cmake>=3.21
    Obtaining dependency information for cmake>=3.21 from https://files.pythonhosted.org/packages/00/64/5ca49f8523ca41deafc6d0bdfb40cfa8f8f3c2abf69de141f69f28791884/cmake-3.27.1-py2.py3-none-win_amd64.whl.metadata
    Using cached cmake-3.27.1-py2.py3-none-win_amd64.whl.metadata (6.9 kB)
  Collecting distro (from scikit-build)
    Using cached distro-1.8.0-py3-none-any.whl (20 kB)
  Collecting packaging (from scikit-build)
    Using cached packaging-23.1-py3-none-any.whl (48 kB)
  Collecting wheel>=0.32.0 (from scikit-build)
    Obtaining dependency information for wheel>=0.32.0 from https://files.pythonhosted.org/packages/28/f5/6955d7b3a5d71ce6bac104f9cf98c1b0513ad656cdaca8ea7d579196f771/wheel-0.41.1-py3-none-any.whl.metadata
    Using cached wheel-0.41.1-py3-none-any.whl.metadata (2.2 kB)
  Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Using cached scikit_build-0.17.6-py3-none-any.whl (84 kB)
  Using cached numpy-1.25.2-cp311-cp311-win_amd64.whl (15.5 MB)
  Using cached cmake-3.27.1-py2.py3-none-win_amd64.whl (34.6 MB)
  Using cached wheel-0.41.1-py3-none-any.whl (64 kB)
  Installing collected packages: cmake, wheel, setuptools, packaging, numpy, distro, scikit-build
  Successfully installed cmake-3.27.1 distro-1.8.0 numpy-1.25.2 packaging-23.1 scikit-build-0.17.6 setuptools-68.0.0 wheel-0.41.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  running egg_info
  writing src\PyNvCodec.egg-info\PKG-INFO
  writing dependency_links to src\PyNvCodec.egg-info\dependency_links.txt
  writing requirements to src\PyNvCodec.egg-info\requires.txt
  writing top-level names to src\PyNvCodec.egg-info\top_level.txt
  reading manifest file 'src\PyNvCodec.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'src\PyNvCodec.egg-info\SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  running dist_info
  creating C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info
  writing C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\PKG-INFO
  writing dependency_links to C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\dependency_links.txt
  writing requirements to C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\requires.txt
  writing top-level names to C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\top_level.txt
  writing manifest file 'C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec.egg-info\SOURCES.txt'
  creating 'C:\Users\PC\AppData\Local\Temp\pip-modern-metadata-r4ehqrsy\PyNvCodec-2.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\pc\anaconda3\envs\ballspot311\lib\site-packages (from PyNvCodec==2.0) (1.25.1)
Building wheels for collected packages: PyNvCodec
  Running command Building wheel for PyNvCodec (pyproject.toml)
  <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html


  --------------------------------------------------------------------------------
  -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Visual Studio 17 2022 x64 v143' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 17 2022

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  -- The C compiler identification is MSVC 19.29.30136.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is MSVC 19.29.30136.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done (1.5s)
  -- Generating done (0.0s)
  -- Build files have been written to: E:/repos/VideoProcessingFramework/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      E:\repos\VideoProcessingFramework\_skbuild\win-amd64-3.11\cmake-build
    Command:
      'C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'E:\repos\VideoProcessingFramework' -G Ninja -D_SKBUILD_FORCE_MSVC=1920 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=E:\repos\VideoProcessingFramework\_skbuild\win-amd64-3.11\cmake-install\src' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\PC\anaconda3\envs\ballspot311\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\PC\anaconda3\envs\ballspot311\libs\python311.lib' '-DPython_EXECUTABLE:PATH=C:\Users\PC\anaconda3\envs\ballspot311\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311\Include' '-DPython_LIBRARY:PATH=C:\Users\PC\anaconda3\envs\ballspot311\libs\python311.lib' '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\PC\anaconda3\envs\ballspot311\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311\Include' '-DPython3_LIBRARY:PATH=C:\Users\PC\anaconda3\envs\ballspot311\libs\python311.lib' '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\numpy\core\include' -DCMAKE_BUILD_TYPE:STRING=Release

  Not searching for unused variables given on the command line.
  -- Populating pybind11
  -- Configuring done (0.1s)
  -- Generating done (0.0s)
  -- Build files have been written to: E:/repos/VideoProcessingFramework/_skbuild/win-amd64-3.11/cmake-build/_deps/pybind11-subbuild
  [1/9] Creating directories for 'pybind11-populate'
  [1/9] Performing download step (download, verify and extract) for 'pybind11-populate'
  -- verifying file...
         file='E:/repos/VideoProcessingFramework/_skbuild/win-amd64-3.11/cmake-build/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.10.0.tar.gz'
  -- File already exists and hash match (skip download):
    file='E:/repos/VideoProcessingFramework/_skbuild/win-amd64-3.11/cmake-build/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.10.0.tar.gz'
    SHA256='eacf582fa8f696227988d08cfc46121770823839fe9e301a20fbce67e7cd70ec'
  -- extracting...
       src='E:/repos/VideoProcessingFramework/_skbuild/win-amd64-3.11/cmake-build/_deps/pybind11-subbuild/pybind11-populate-prefix/src/v2.10.0.tar.gz'
       dst='E:/repos/VideoProcessingFramework/_skbuild/win-amd64-3.11/cmake-build/_deps/pybind11-src'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  [2/9] No update step for 'pybind11-populate'
  [3/9] No patch step for 'pybind11-populate'
  [5/9] No configure step for 'pybind11-populate'
  [6/9] No build step for 'pybind11-populate'
  [7/9] No install step for 'pybind11-populate'
  [8/9] No test step for 'pybind11-populate'
  [9/9] Completed 'pybind11-populate'
  CMake Deprecation Warning at _skbuild/win-amd64-3.11/cmake-build/_deps/pybind11-src/CMakeLists.txt:8 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  -- pybind11 v2.10.0
  -- TC_FFMPEG_ROOT/bin/=/bin/
  -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
  -- TC_FFMPEG_INCLUDE_DIR=""
  -- TC_FFMPEG_ROOT=""
  -- TC_FFMPEG_LIBRARY_DIR=""
  CMake Error at src/TC/CMakeLists.txt:164 (message):
    Could not find avfilter_LIBRARY! Please set TC_FFMPEG_ROOT to indicate its
    location!
  Call Stack (most recent call first):
    src/TC/CMakeLists.txt:178 (link_av_component)


  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
      env = cmkr.configure(
            ^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
      raise SKBuildError(msg)

  An error occurred while configuring with CMake.
    Command:
      'C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'E:\repos\VideoProcessingFramework' -G Ninja -D_SKBUILD_FORCE_MSVC=1920 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=E:\repos\VideoProcessingFramework\_skbuild\win-amd64-3.11\cmake-install\src' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\PC\anaconda3\envs\ballspot311\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\PC\anaconda3\envs\ballspot311\libs\python311.lib' '-DPython_EXECUTABLE:PATH=C:\Users\PC\anaconda3\envs\ballspot311\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311\Include' '-DPython_LIBRARY:PATH=C:\Users\PC\anaconda3\envs\ballspot311\libs\python311.lib' '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\PC\anaconda3\envs\ballspot311\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\PC\anaconda3\envs\ballspot311\Include' '-DPython3_LIBRARY:PATH=C:\Users\PC\anaconda3\envs\ballspot311\libs\python311.lib' '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\PC\AppData\Local\Temp\pip-build-env-2l8hwd1n\overlay\Lib\site-packages\numpy\core\include' -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      E:\repos\VideoProcessingFramework
    Working directory:
      E:\repos\VideoProcessingFramework\_skbuild\win-amd64-3.11\cmake-build
  Please see CMake's output for more information.

  error: subprocess-exited-with-error

  × Building wheel for PyNvCodec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\PC\anaconda3\envs\ballspot311\python.exe' 'C:\Users\PC\anaconda3\envs\ballspot311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' build_wheel 'C:\Users\PC\AppData\Local\Temp\tmpnrt9bs1s'
  cwd: E:\repos\VideoProcessingFramework
  Building wheel for PyNvCodec (pyproject.toml) ... error
  ERROR: Failed building wheel for PyNvCodec
Failed to build PyNvCodec
ERROR: Could not build wheels for PyNvCodec, which is required to install pyproject.toml-based projects

**Comment by jonahpearl** [comment]
I had the same error. I changed all the backslashes in my path to forward slashes and then it worked fine. Credit where it's due, the README does indeed use forward slashes, but I think we could be forgiven for defaulting to backslashes on windows. No clue why this occurs!
