### ISSUE TITLE
Unable to import PyNvCodec as nvc

### ISSUE THREAD

**Issue by KevinZ-718** [NVIDIA/VideoProcessingFramework#566]
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyNvCodec as nvc
Traceback (most recent call last):
  File "/home/kevin/anaconda3/lib/python3.11/site-packages/PyNvCodec/__init__.py", line 17, in <module>
    from ._PyNvCodec import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kevin/anaconda3/lib/python3.11/site-packages/PyNvCodec/__init__.py", line 21, in <module>
    raise RuntimeError("Failed to import native module _PyNvCodec! "
RuntimeError: Failed to import native module _PyNvCodec! Please check whether "/home/kevin/anaconda3/lib/python3.11/site-packages/PyNvCodec/_PyNvCodec.cpython-311-x86_64-linux-gnu.so" exists and can find all library dependencies (CUDA, ffmpeg).
On Unix systems, you can use `ldd` on the file to see whether it can find all dependencies.
On Windows, you can use "dumpbin /dependents" in a Visual Studio command prompt or
https://github.com/lucasg/Dependencies/releases.

**Comment by RomanArzumanyan** [comment]
Hi @KevinZ-718 

Please check out https://github.com/RomanArzumanyan/VALI which is actively developed and maintained VPF spin-off. It has compatible API and module naming. In case your issue reproduces with VALI, just duplicate it there.

Unfortunately there's no active development going in VPF public repo now, so I won't be able to help you here.
