### ISSUE TITLE
AttributeError: module 'PyNvCodec' has no attribute 'PyNvDecoder'

### ISSUE THREAD

**Issue by leviethung2103** [NVIDIA/VideoProcessingFramework#78]
**Describe the bug**
Hi author, 

I've complied succesfully the VideoProcessingFramework. However, when I am trying`SampleDecode.py` with my video. It causes the error: `AttributeError: module 'PyNvCodec' has no attribute 'PyNvDecoder'.

**To Reproduce**
1. Activate the environment that link to VideoFrameworkLibrary
2. `python SampleDecode.py 0 ../test_videos/input/4K.MP4 ../test_videos/output/4K_decode.mp4`
`
3. The error is 
```
Traceback (most recent call last):
  File "SampleDecode.py", line 55, in <module>
    decode(gpuID, encFilePath, decFilePath)
  File "SampleDecode.py", line 22, in decode
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
AttributeError: module 'PyNvCodec' has no attribute 'PyNvDecoder'
```

**Expected behavior**
Run the code sucessfully.

**Screenshots**
Here is screenshot after compiling VPF and install 
![Screenshot from 2020-07-16 08-57-14](https://user-images.githubusercontent.com/16741872/87617776-6422e980-c742-11ea-8e57-f4fc37c0aaba.png)

**Desktop (please complete the following information):**
 - OS: Linux 18.04
 - Nvidia driver version: 440.100
 - CUDA Version 10.1
 - Video Codec SDK Version 10.0.26
 - Python Version: 3.7
- FFMPEG version: 3.4, compiled from source just as explained in the wiki

**Additional context**
cmake optinon that I've used
```
cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="0" \
  -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" 
```

Thanks in advance, best regards, and I wait for your reply,

**Comment by leviethung2103** [comment]
That's so weird because I can import the `PyNvCodec` package successfully. 
![Screenshot from 2020-07-16 09-11-33](https://user-images.githubusercontent.com/16741872/87618585-69813380-c744-11ea-8627-95e1e7f994b5.png)

**Comment by leviethung2103** [comment]
I've solved the problem by run the `SampleDecode.py` in `install/bin` folder.
