### ISSUE TITLE
ModuleNotFoundError on sample running right after installation

### ISSUE THREAD

**Issue by krydm** [NVIDIA/VideoProcessingFramework#92]
**Describe the bug**
ModuleNotFoundError: No module named 'PyNvCodec' on attempt to run SampleDecode.py right after VPF installation

**To Reproduce**
I’m installing everything following Wiki instructions, except:
a)not building ffmpeg and using the stock one(/usr/bin/ffmpeg)
b)my nvcc is in /usr/bin/nvcc
c)without PyTorch(don’t need it)
d)libpython path is returned by python3 find_libpython.py and it is /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0

So I’m running cmake(sorry, I'm not sure how to get rid of the strikethrough below)
```bash
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ cmake ..   -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG"   -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK"   -DGENERATE_PYTHON_BINDINGS:BOOL="1"   -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0   -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Searching for FFmpeg libs in /usr/bin/ffmpeg/lib
-- Searching for FFmpeg headers in /usr/bin/ffmpeg/include
-- Searching for Video Codec SDK headers in /home/ericsson/Video_Codec_SDK_10.0.26/include folder
-- Searching for Video Codec SDK headers in /home/ericsson/Video_Codec_SDK_10.0.26/Interface folder
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (found suitable version "3.8.2", minimum required is "3.5") 
-- Found PythonInterp: /usr/bin/python3.7 (found version "3.7.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ericsson/VideoProcessingFramework/build
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ 
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ make && make install
Scanning dependencies of target TC_CORE
[  6%] Building CXX object PyNvCodec/TC/TC_CORE/CMakeFiles/TC_CORE.dir/src/Task.cpp.o
[ 12%] Building CXX object PyNvCodec/TC/TC_CORE/CMakeFiles/TC_CORE.dir/src/Token.cpp.o
[ 18%] Linking CXX shared library libTC_CORE.so
[ 18%] Built target TC_CORE
Scanning dependencies of target TC
[ 25%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/MemoryInterfaces.cpp.o
[ 31%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o
[ 37%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/TasksColorCvt.cpp.o
[ 43%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/FFmpegDemuxer.cpp.o
[ 50%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NvDecoder.cpp.o
[ 56%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NvEncoder.cpp.o
/home/ericsson/VideoProcessingFramework/PyNvCodec/TC/src/NvEncoder.cpp: In member function ‘void NvEncoder::CreateEncoder(const NV_ENC_INITIALIZE_PARAMS*)’:
/home/ericsson/VideoProcessingFramework/PyNvCodec/TC/src/NvEncoder.cpp:232:40: warning: ‘NV_ENC_PRESET_DEFAULT_GUID’ is deprecated: WILL BE REMOVED IN A FUTURE VIDEO CODEC SDK VERSION [-Wdeprecated-declarations]
```

Then there are several more warnings of this kind, and cmake finishes OK, and I run `make && make install`

Then I check the cuda bindings and follow the instructions again, and get ModuleNotFoundError on trying to run a sample:
```bash
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ ldd ../install/bin/PyNvCodec.cpython-37m-x86_64-linux-gnu.so | grep libcuda
	libcuda.so.1 => /lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f88691d4000)
	libcudart.so.10.1 => /lib/x86_64-linux-gnu/libcudart.so.10.1 (0x00007f8866cd1000)
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ ldd ../install/bin/PyNvCodec.cpython-37m-x86_64-linux-gnu.so | grep libnvc
	libnvcuvid.so.1 => /lib/x86_64-linux-gnu/libnvcuvid.so.1 (0x00007f78502e6000)
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ cd ../install/bin
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ export LD_LIBRARY_PATH=$PATH_TO_FFMPEG/lib:$LD_LIBRARY_PATH
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ python3 ./SampleDecode.py
Traceback (most recent call last):
  File "./SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ModuleNotFoundError: No module named 'PyNvCodec'
```

**Expected behavior**
to get a sample running ;)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04.1
 - Nvidia driver version 440.100
 - CUDA Version 10.2
 - Video Codec SDK Version 10.0.26
 - Python Version 3.8

**Additional context**
Just in case:
ericsson@rat-zbox-n72070v-01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```bash
ericsson@rat-zbox-n72070v-01:~$ nvidia-smi
Sat Aug 15 03:35:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8     6W /  N/A |    231MiB /  7981MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1055      G   /usr/lib/xorg/Xorg                            29MiB |
|    0      1805      G   /usr/lib/xorg/Xorg                            72MiB |
|    0      1863      G   /usr/bin/gnome-shell                         113MiB |
|    0      1872      G   /opt/teamviewer/tv_bin/TeamViewer              2MiB |
+-----------------------------------------------------------------------------+
```

**Comment by rarzumanyan** [comment]
HI @krydm 

I've sligthly edited your post (changed style for bash snippets).

>ModuleNotFoundError: No module named 'PyNvCodec' on attempt to run SampleDecode.py right after VPF installation

This often happens when VPF was linked against one Python version and launched with another.
Please check that you're actually running python 3.8 when launching the sample first.
I've tested VPF with Ubuntu 20.04 and Pyton 3.8 so theoretically this combo shouldn't cause such a problem.

**Comment by krydm** [comment]
Hi @rarzumanyan 
Thanks for cleaning my snippets and sorry for the mess.

I'm not sure whether there is some other full-proof check of the python version, but here is my output:

`ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ python3 ./SampleDecode.py
Traceback (most recent call last):
  File "./SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ModuleNotFoundError: No module named 'PyNvCodec'
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ python3.8 ./SampleDecode.py
Traceback (most recent call last):
  File "./SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ModuleNotFoundError: No module named 'PyNvCodec'
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ python3.7 ./SampleDecode.py
Traceback (most recent call last):
  File "./SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ImportError: Python version mismatch: module was compiled for Python 3.8, but the interpreter version is incompatible: 3.7.8 (default, Jun 29 2020, 04:26:04) 
[GCC 9.3.0].
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ python3 -V
Python 3.8.2
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ 
`
Looks like it is indeed 3.8. Or maybe there are some deeper checks I miss? TIA

**Comment by rarzumanyan** [comment]
@krydm 

Can you just run
```bash
 ldd ../install/bin/PyNvCodec.cpython-37m-x86_64-linux-gnu.so
```
to see what libraries are loaded? Looks like some of them are missing.

>Btw, how do you do it?

I encapsulate code snippet within 
\```bash 
\#Your bash code
\```
block

**Comment by krydm** [comment]
@rarzumanyan here it is:
```bash
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ ldd PyNvCodec.cpython-37m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffe1b3a2000)
	libTC.so => /home/ericsson/VideoProcessingFramework/install/bin/libTC.so (0x00007f713aecf000)
	libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f713a957000)
	libTC_CORE.so => /home/ericsson/VideoProcessingFramework/install/bin/libTC_CORE.so (0x00007f713a94f000)
	libcuda.so.1 => /lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f713972e000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f713954d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7139530000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f713933e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f713931b000)
	libnvcuvid.so.1 => /lib/x86_64-linux-gnu/libnvcuvid.so.1 (0x00007f7138e07000)
	libavutil.so.56 => /lib/x86_64-linux-gnu/libavutil.so.56 (0x00007f7138cde000)
	libavcodec.so.58 => /lib/x86_64-linux-gnu/libavcodec.so.58 (0x00007f7137721000)
	libavformat.so.58 => /lib/x86_64-linux-gnu/libavformat.so.58 (0x00007f71374a7000)
	libcudart.so.10.1 => /lib/x86_64-linux-gnu/libcudart.so.10.1 (0x00007f713722b000)
	libnppig.so.10 => /lib/x86_64-linux-gnu/libnppig.so.10 (0x00007f7135759000)
	libnppicc.so.10 => /lib/x86_64-linux-gnu/libnppicc.so.10 (0x00007f713511c000)
	libnppidei.so.10 => /lib/x86_64-linux-gnu/libnppidei.so.10 (0x00007f713472c000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f71346fe000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f71346e0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f71346da000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f71346d5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7134586000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f713457b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f713b051000)
	libva-drm.so.2 => /lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007f7134574000)
	libva.so.2 => /lib/x86_64-linux-gnu/libva.so.2 (0x00007f713454b000)
	libva-x11.so.2 => /lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007f7134543000)
	libvdpau.so.1 => /lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007f713453d000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f7134400000)
	libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f71343ec000)
	libOpenCL.so.1 => /lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f71341df000)
	libswresample.so.3 => /lib/x86_64-linux-gnu/libswresample.so.3 (0x00007f71341bd000)
	libvpx.so.6 => /lib/x86_64-linux-gnu/libvpx.so.6 (0x00007f7133f85000)
	libwebpmux.so.3 => /lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007f7133d7b000)
	libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f7133b12000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7133aeb000)
	librsvg-2.so.2 => /lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007f71331f9000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f7133199000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f7133070000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f7132f4d000)
	libzvbi.so.0 => /lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007f7132ebe000)
	libsnappy.so.1 => /lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f7132eb3000)
	libaom.so.0 => /lib/x86_64-linux-gnu/libaom.so.0 (0x00007f7132a13000)
	libcodec2.so.0.9 => /lib/x86_64-linux-gnu/libcodec2.so.0.9 (0x00007f7131c2f000)
	libgsm.so.1 => /lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f7131c20000)
	libmp3lame.so.0 => /lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f7131ba8000)
	libopenjp2.so.7 => /lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f7131b52000)
	libopus.so.0 => /lib/x86_64-linux-gnu/libopus.so.0 (0x00007f7131af3000)
	libshine.so.3 => /lib/x86_64-linux-gnu/libshine.so.3 (0x00007f71318e6000)
	libspeex.so.1 => /lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f71318c8000)
	libtheoraenc.so.1 => /lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f713188b000)
	libtheoradec.so.1 => /lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f713186b000)
	libtwolame.so.0 => /lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007f7131845000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f7131817000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f713176a000)
	libwavpack.so.1 => /lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007f713173e000)
	libx264.so.155 => /lib/x86_64-linux-gnu/libx264.so.155 (0x00007f7131480000)
	libx265.so.179 => /lib/x86_64-linux-gnu/libx265.so.179 (0x00007f7130512000)
	libxvidcore.so.4 => /lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007f71303ff000)
	libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f7130243000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f7130230000)
	libgme.so.0 => /lib/x86_64-linux-gnu/libgme.so.0 (0x00007f71301e3000)
	libopenmpt.so.0 => /lib/x86_64-linux-gnu/libopenmpt.so.0 (0x00007f712fff6000)
	libchromaprint.so.1 => /lib/x86_64-linux-gnu/libchromaprint.so.1 (0x00007f712ffe0000)
	libbluray.so.2 => /lib/x86_64-linux-gnu/libbluray.so.2 (0x00007f712ff8f000)
	libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f712fdb7000)
	libssh-gcrypt.so.4 => /lib/x86_64-linux-gnu/libssh-gcrypt.so.4 (0x00007f712fd2b000)
	libnppc.so.10 => /lib/x86_64-linux-gnu/libnppc.so.10 (0x00007f712fab0000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f712fa9b000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f712fa93000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f712fa67000)
	libsoxr.so.0 => /lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007f712f9fc000)
	libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f712f9f0000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f712f9c8000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f712f7e7000)
	libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f712f7d3000)
	libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f712f784000)
	libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007f712f778000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f712f705000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f712f65e000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f712f615000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f712f556000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f712f51e000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f712f519000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f712f50a000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f712f300000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007f712f2f1000)
	libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f712f2e4000)
	libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f712f0fe000)
	libmpg123.so.0 => /lib/x86_64-linux-gnu/libmpg123.so.0 (0x00007f712f09e000)
	libvorbisfile.so.3 => /lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007f712f093000)
	libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f712ef5b000)
	libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f712ef3a000)
	libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f712edb8000)
	libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f712eda2000)
	libnettle.so.7 => /lib/x86_64-linux-gnu/libnettle.so.7 (0x00007f712ed68000)
	libhogweed.so.5 => /lib/x86_64-linux-gnu/libhogweed.so.5 (0x00007f712ed30000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f712ecaa000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f712eb8c000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f712eb69000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f712eb1c000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f712eb16000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f712eb0c000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f712eaca000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f712eac4000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f712ea64000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f712ea39000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f712ea1d000)
	libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f712ea02000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f712e9e5000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007f712e9da000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f712e8d5000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f712e8cc000)
	libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f712ce09000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f712cd2c000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f712ccfb000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f712ccf4000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f712cce5000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f712ccc9000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f712cc72000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f712cbe2000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f712cbd8000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f712cbab000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f712cba2000)
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ 

```
block

**Comment by rarzumanyan** [comment]
@krydm 

It looks like all the libraries are there.
One more approach to this problem is to trace the module loading process.

Let's make the simplest script, call it LoadModule.py:
```python
import sys
print('Module Search Path:')
print(sys.path)

import PyNvCodec as nvc
```

Then put it in the VPF install directory and run it:
```cmd
C:\GitHub\VideoProcessingFramework\install\bin>python -v LoadModule.py 
```

In the output I can see the module search path and where the module is actually loaded from:
```
Module Search Path:
['C:\\GitHub\\VideoProcessingFramework\\install\\bin', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\python37.zip', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\DLLs', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\lib', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\rarzumanyan\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\Pythonwin']

%Unrelevant output ommited

# extension module 'PyNvCodec' loaded from 'C:\\GitHub\\VideoProcessingFramework\\install\\bin\\PyNvCodec.cp37-win_amd64.pyd'
# extension module 'PyNvCodec' executed from 'C:\\GitHub\\VideoProcessingFramework\\install\\bin\\PyNvCodec.cp37-win_amd64.pyd'
import 'PyNvCodec' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000002368CC615C8>
```

Can you do the same to check where the interpreter expects to see `PyNvCodec`?

**Comment by krydm** [comment]
@rarzumanyan yes, did it, it does show me VideoProcessingFramework install bin in the search path, but still can't find the module:
```bash
Module Search Path:
['/home/ericsson/VideoProcessingFramework/install/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/ericsson/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

#ommiting

Traceback (most recent call last):
  File "LoadModule.py", line 5, in <module>
    import PyNvCodec as nvc
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyNvCodec'
```

**Comment by rarzumanyan** [comment]
@krydm 

That's really strange.
Can you try other Python version (3.7) or distro (Anaconda) instead?

**Comment by krydm** [comment]
@rarzumanyan lemme try it. But you did it with 3.8, right?
BTW, I've added ls -la output of the install/bin just in case, see updated previous msg

**Comment by rarzumanyan** [comment]
@krydm 

The python module name shows that it’s built for python 3.7

**Comment by krydm** [comment]
Hi @rarzumanyan 
I'm trying to use python3.7, running 
```bash
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/build$ cmake ..   -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG"   -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK"   -DGENERATE_PYTHON_BINDINGS:BOOL="1"   -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0   -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.7
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Searching for FFmpeg libs in /usr/bin/ffmpeg/lib
-- Searching for FFmpeg headers in /usr/bin/ffmpeg/include
-- Searching for Video Codec SDK headers in /home/ericsson/Video_Codec_SDK_10.0.26/include folder
-- Searching for Video Codec SDK headers in /home/ericsson/Video_Codec_SDK_10.0.26/Interface folder
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (found suitable version "3.8.2", minimum required is "3.5") 
-- Found PythonInterp: /usr/bin/python3.7 (found version "3.7.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ericsson/VideoProcessingFramework/build
```
Note, I've even added -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.7 to cmake to be sure 3.7 is used
....(all the rest of the process)
However, on the final run of example I'm getting 
```bash
ericsson@rat-zbox-n72070v-01:~/VideoProcessingFramework/install/bin$ python3.7 ./SampleDecode.py
Traceback (most recent call last):
  File "./SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ImportError: Python version mismatch: module was compiled for Python 3.8, but the interpreter version is incompatible: 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0].
```
No idea how to switch this thing to 3.7. It looks like it continues to build for 3.8.

I'm trying to install Anaconda, but for some reason curl seem to be stalled forever. It's probably some local problems with my network, so for now I'm just reporting the failure with 3.7

**Comment by krydm** [comment]
> The python module name shows that it’s built for python 3.7

You mean 37m in the name PyNvCodec.cpython-37m-x86_64-linux-gnu.so?

Still, I'm getting ImportError trying to run 3.7

**Comment by rarzumanyan** [comment]
@krydm 

```bash
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (found suitable version "3.8.2", minimum required is "3.5") 
-- Found PythonInterp: /usr/bin/python3.7 (found version "3.7.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0
```
Clearly shows that CMake has found Python 3.7 libraries and shall build the `PyNvCodec` for Python 3.7.
However, the Python libs version is determined as 3.8.2.

I suppose some black magic happens within the multiple Python versions handling.
The only other advice I can give is to remove all the Python 3 versions except one you want to stay with.
Say, remove all the Python 3 stuff  except 3.8 completely, delete CMake cache and start VPF build process from scratch.

**Comment by krydm** [comment]
@rarzumanyan 

Well, renaming didn't help.
But yesss! I've removed completely all 3.7-related stuff and voila -- everything started to work like a snap.
I guess there still should be a way to manage several python versions without going to all this mixed hell, but for now I'm absolutely happy.
Many thanks!

**Comment by rarzumanyan** [comment]
@krydm 

Great news, I'm glad it works.
Closing this issue as fixed.

**Comment by jiashenC** [comment]
I have faced similar issue that cmake does not link the expected python version. I am able to overcome this by adding explicit python flags described in [this stackoverflow post](https://stackoverflow.com/questions/15291500/i-have-2-versions-of-python-installed-but-cmake-is-using-older-version-how-do).

**Comment by NguyenVanThanhHust** [comment]
I don't know why but use `python3 setup.py install` on jetson docker could cause problem, should use `pip install .` as in Readme.md instead.
